# Generated by Django 4.0.8 on 2022-10-27 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Intern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slackUsername', models.CharField(default='', max_length=50)),
                ('backend', models.BooleanField(default='True')),
                ('age', models.SmallIntegerField()),
                ('bio', models.TextField()),
            ],
        ),
    ]
